source = ./env.conf
source = ./binds.conf
source = ./monitors.conf
source = ./input.conf
source = ./looknfeel.conf
source = ./windowrules.conf
source = ./autoexec.conf

env = GTK_IM_MODULE,ibus
env = QT_IM_MODULE,ibus
env = XMODIFIERS,@im=ibus
env = SDL_IM_MODULE,ibus

exec-once = ibus-daemon -drx
