#!/bin/bash

ACTION=$(echo -e "Logout\nShutdown\nReboot\nSuspend\nLock" | wofi --dmenu --prompt "Power")

case "$ACTION" in
    Logout)
        hyprctl dispatch exit
        ;;
    Shutdown)
        ~/dotfiles/scripts/powerctl poweroff
        ;;
    Reboot)
        ~/dotfiles/scripts/powerctl reboot
        ;;
    Suspend)
        ~/dotfiles/scripts/powerctl suspend
        ;;
    Lock)
        hyprlock
        ;;
esac
