#!/bin/zsh

ACTION=$(echo -e "Logout\nShutdown\nReboot\nSuspend\nLock" | wofi --dmenu --prompt "Power")

case "$ACTION" in
    Logout)
        niri msg action quit
        ;;
    Shutdown)
        ~/dotfiles/scripts/powerctl poweroff
        ;;
    Reboot)
        ~/dotfiles/scripts/powerctl reboot
        ;;
    Suspend)
        ~/dotfiles/scripts/powerctl suspend
        ;;
    Lock)
        swaylock -f
        ;;
esac
