#!/bin/bash

if ! pgrep -x wf-recorder > /dev/null; then
    echo '{"text": "", "tooltip": "", "class": ""}'
else
    echo '{"text": "󰔊", "tooltip": "Screen recording in progress", "class": "recording"}'
fi
