#!/bin/bash

STATUS_FILE=/tmp/screenrecording-status

if [ -f "$STATUS_FILE" ]; then
    pid=$(cat "$STATUS_FILE")
    if kill -0 "$pid" 2>/dev/null; then
        kill "$pid"
        rm -f "$STATUS_FILE"
        notify-send "Screen recording stopped"
    else
        rm -f "$STATUS_FILE"
    fi
else
    wf-recorder -f "$HOME/Videos/$(date +%Y%m%d_%H%M%S).mp4" &
    echo $! > "$STATUS_FILE"
    notify-send "Screen recording started"
fi
